# Generated by Django 2.2.7 on 2020-04-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
