# Generated by Django 2.2.7 on 2020-04-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.computer'),
        ),
    ]
