# Generated by Django 2.2.7 on 2020-04-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20200403_0322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
