# Generated by Django 2.2.7 on 2020-04-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
